### ISSUE TITLE
Stringified object does not get masked

### ISSUE THREAD

**Issue by matthiasheyman** [slippyex/data-guardian#8]
First of all,  thanks for the nice library. 
I just have this remark:

When I first stringify an object, and then execute maskString, I still get the password as readable text.
`
const data = '{"username":"myuser","password":"something"}';
const result = maskString(data);
`
result will still contain the exact same content as data.

**Comment by slippyex** [comment]
Hey @matthiasheyman ... I just looked into your reported issue and found that I can fix it quite easily. I just published version 1.1.3 which should handle your case as expected.

**Comment by matthiasheyman** [comment]
Thanks!
